### ISSUE TITLE
How does the target application accesses its injected files?

### ISSUE THREAD

**Issue by nhh** [maja42/ember#4]
I do understand how it works, but I think I dont understand how this is used by the target application? (I assume the target is also a go binary with a custom FS implementation.)

I would like to use this to produce self contained applications. For example a ui lib that takes user-code and embeds it in itself

**Comment by maja42** [comment]
The first example in the readme shows how the target application can access the embedded content:
https://github.com/maja42/ember?tab=readme-ov-file#access-embedded-files-from-within-the-target-application

**Comment by maja42** [comment]
Does this answer your question?

**Comment by nhh** [comment]
A classical case of rtfm! Consider this case closed 🙏
